### ISSUE TITLE
Wrong key combination to stop `squeue --iterate`

### ISSUE THREAD

**Issue by tdanhorn** [ResearchComputing/Documentation#107]
In `Documentation/docs/running-jobs/slurm-commands.md` (line 51), the command to stop `squeue --iterate=n` is given as `Ctrl-z`.  This will suspend the process in the background, rather than actually stop it.  (If this is in fact desired, you need to mention the `fg` command to bring it back, and maybe `jobs` to list the suspended and running shell jobs.)  The key combination to actually kill this (or any other) process is `Ctrl-c`.

**Comment by dtrahan41** [comment]
Ah yes,
