### ISSUE TITLE
duo.colorado.edu page has changed

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/Documentation#13]
re: https://github.com/ResearchComputing/Research-Computing-User-Tutorials/wiki/FAQs#i-have-a-new-phone-how-do-i-move-my-duo-onto-it

This is what I am telling people for the revised site:
If your phone number is the same you can self-manage devices at duo.colorado.edu . After the Federated login choose the 'Settings' menu to add or manage devices. 
You then have to use Phone Call or SMS as a 2nd factor, Phone Call is more straightforward.   If your phone number has changed please let us know and we'll send you a new enrollment email.

**Comment by rctraining** [comment]
I noticed this today and I will amend the page. Thanks for letting me know!

-Daniel T
