### ISSUE TITLE
update definition of --mem to reflect Slurm changes to Blanca, Summit, and Alpine 

### ISSUE THREAD

**Issue by LRFreeborn** [ResearchComputing/Documentation#179]
change --mem def to something along the lines of

> The total memory (per node requested) required to complete the job. The number of cores allocated to your job does not scale with the total memory requested, but you will be charged # cores = total memory / RAM per core.  Units can be specified with the suffixes: K,M,G,T (default M)

We should confirm with Andy that the description of the charges is correct.

**Comment by ghidalgo93** [comment]
Layla resolved and updated
