### ISSUE TITLE
RC-2800 -- Remove mentions of Summit from documentation 

### ISSUE THREAD

**Issue by b-reyes** [ResearchComputing/Documentation#230]
General items to complete:
- [x] Removal of Summit related material
    - [x] For the page `clusters/summit` we need to remove the page material and replace it with a statement explaining that summit can no longer be used. Additionally, a citation should be added to this page for summit and a statement that tells users to email us if they want info on summit 
    - [x] Remove `running-jobs/ssky.md` 

Brandon's sections:
- [x] programming/MPIBestpractices.md
- [x] programming/MPI-Fortran.md
- [x] gateways/OnDemand.md
- [x] gateways/jupyterhub.md
- [x] compute/monitoring-resources.md
- [x] compute/filesystems.md
- [x] compute/data-transfer.md
- [x] clusters/alpine/quick-start.md
- [x] clusters/alpine/condo-fairshare-and-resource-access.md
- [x] cloud/slurm-integration.md
- [x] cloud/cumulus.md
- [x] software/ContainerizationonSummit.md
- [x] clusters/alpine/software.md
- [x] tutorials/cumulus3.md
- [x] storage/scratch/summit_scratch.md
- [x] storage/scratch/index.rst

Trevor's sections:
- [x] running-jobs/ssky.md
- [x] clusters/summit
- [x] compute/compiling.md
- [x] clusters/alpine/moving-from-summit.md
- [x] clusters/alpine/important-notes.md
- [x] cloud/instance-creation.md
- [x] additional-resources/policies.md
- [x] additional-resources/other.md
- [x] additional-resources/csu-xsede-usernames.md
- [x] access/logging-in.md
- [x] docs/index.rst
- [x] clusters/alpine/index.rst
- [x] docs/faq.md
- [x] software/gaussian.md
- [x] programming/running-mpi-best-practices.md
- [x] running-jobs/running-apps-with-jobs.md~
- [x] running-jobs/job-resources.md~
- [x] running-jobs/interactive-jobs.md~
- [ ] All files in the directory `Templates`

**Comment by Trevhall52** [comment]
Didn't mess with other.md too much - this is the facilities statement. Though it contains mentions of Summit, JH, and EnginFrame, will likely confirm with leadership before making any changes here

**Comment by b-reyes** [comment]
Within `compute/monitoring-resources.md` we have an `XDMoD` section. Some pictures include summit in the output. Once XDMoD has been updated we need to also update these pictures. For now, I just left them alone.

**Comment by LRFreeborn** [comment]
This work is tied to [RC-2800](https://jira.colorado.edu/browse/RC-2800).

**Comment by LRFreeborn** [comment]
@Trevhall52 did we decide you were going to remove Templates?

**Comment by b-reyes** [comment]
This issue was addressed, but accidentally not closed ... closing
