### ISSUE TITLE
Updates for Next Annual Review 

### ISSUE THREAD

**Issue by LRFreeborn** [ResearchComputing/Documentation#263]
- Update text mentioning 2021 timeline in zfs_snapshots.md
- Note that jobs that support GUI apps on Alpine/Blanca can now be easily started from a terminal on the "core desktop" nodes by first typing "ssh -X login-ci1", then "module load slurm/<cluster>".

**Comment by Trevhall52** [comment]
- Review and add X11 instructions for windows users (PR #264 written for this purpose) 
- Note that DTNs are scp-only at user request
- Revisit formatting changes

**Comment by LRFreeborn** [comment]
add instructions for setting up `scron` jobs
