### ISSUE TITLE
Add branching link or content for CU Anschutz-specific guidance on logging in

### ISSUE THREAD

**Issue by d33bs** [ResearchComputing/Documentation#284]
Thanks for the great documentation and efforts surrounding Research Computing services and the documentation found here! I noticed that the [Logging In](https://curc.readthedocs.io/en/latest/access/logging-in.html) page doesn't include any notes for CU Anschutz users. I recognize one might expect a CU Anschutz user to understand ahead of time that they are to use the RMACC methods, but this could be confusing especially for first-time users or newcomers to CU. I'd propose a small note about CU Anschutz (and other CU campuses?) login procedures differing on this page. This could be a small gesture to avoid user confusion across campuses (and perhaps reduce the number of emails, service cases, or lost usage). An additional reminder might be needed near the SSH section, which also significantly differs for CU Anschutz users (who may otherwise scan or search and open the logging in page).

**Comment by b-reyes** [comment]
@d33bs thank you very much for bringing this to our attention and we apologize for the delay. In PR #374 last week we addressed your concerns. We now have tabs for the different institutions. In particular, in the [Getting access to CURC resources](https://curc.readthedocs.io/en/latest/getting_started/logging-in.html#getting-access-to-curc-resources) section we address your concerns about logging into our resources via SSH and link to a page we have that helps AMC users setup SSH access.

**Comment by d33bs** [comment]
Thanks @b-reyes !
