### ISSUE TITLE
update DTN23 and data transfer documentation to reflect capabilities enabled by rbash

### ISSUE THREAD

**Issue by LRFreeborn** [ResearchComputing/Documentation#300]
Some or all of these changes should be incorporated into our pages on the DTNs and/or data transfers:
- dnt23 nodes are no longer 'no login'; users from any institution can ssh into dtn23.rc.colorado.edu from a login node or compute node and run a limited set of commands, defined through rbash
- anyone who has uploaded a key to the RMACC CILogon registry and is on one of the approved VPNs can perform passwordless data transfers on the DTNs
- CU Boulder users who have a key in /home/$USER to enable passwordless data transfers will need to migrate to CILogon at some point

**Comment by b-reyes** [comment]
@LRFreeborn says this has been addressed
