### ISSUE TITLE
Typo in "Using MPI with Fortran" tutorial

### ISSUE THREAD

**Issue by laurasootes** [ResearchComputing/Documentation#312]
https://github.com/ResearchComputing/Documentation/blame/78ace6f492b3113efbd2e5bf7b4f2d9eb6e4c5f4/docs/programming/MPI-Fortran.md#L292

The call to MPI_BARRIER in the "Using MPI with Fortran" tutorial (Documentation/docs/programming/MPI-Fortran.md) uses the argument `i_error` instead of the defined `ierror`.

**Comment by mohalkh5** [comment]
@laurasootes Thank you for bringing this to our attention. We have addressed the issue in PR#324
