### ISSUE TITLE
Feedback form link no longer exists

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#317]
On the main page of the Research Computing User Guide, there is a hyperlink entitled "Can't find what you need? Provide feedback on the CURC docs!".  The hyperlink goes to this: 

https://forms.gle/bSQEeFrdvyeQWPtW9

...which in turn is no longer valid.

**Comment by b-reyes** [comment]
We can include GH edit button or create an issue button.

**Comment by b-reyes** [comment]
@jreiland this is directly related to your work in [RC-4392](https://jira.colorado.edu/browse/RC-4392). I don't think we need to add a GH edit/issue button to address this, but if you do want to add those buttons I am not opposed to that.

**Comment by b-reyes** [comment]
Addressed by @jreiland in PR #362
