### ISSUE TITLE
Incorrect Commands for Running MPI with Intel on Blanca General Nodes

### ISSUE THREAD

**Issue by SchneiderCode** [ResearchComputing/Documentation#326]
The MPI Best Practices page needs to be updated to use the most recent commands for turning off high-speed internode communication. Specifically, the Intel command is not correct for the most recent version of Intel MPI installed on the Blanca nodes. 

TODO: 
Update the Intel command to be : 

Intel - Single Node Jobs:
mpirun -genv I_MPI_FABRICS=shm <other arguments>

Intel - Multi-Node Jobs (Constain jobs to EDR IB (InfiniBand)):
mpirun -genv --contraint=edr <other arguments>

Documentation Page: https://curc.readthedocs.io/en/latest/programming/MPIBestpractices.html#running-mpi-on-blanca 

Relevant Notes can be found in the ServiceNow Ticket: INC1149445

**Comment by b-reyes** [comment]
Being addressed in PR #336

**Comment by jreiland** [comment]
@SchneiderCode Can you clarify the line numbers that are incorrect?

**Comment by SchneiderCode** [comment]
The area to update would the Intel Commands, listed under "General Blanca Node"

**Comment by b-reyes** [comment]
Addressed by @jreiland in PR #336
