### ISSUE TITLE
Update numbers in Cluster Summary section on Alpine Quick Start page

### ISSUE THREAD

**Issue by jreiland** [ResearchComputing/Documentation#345]
The node counts and specs for the nodes are out of date in the Cluster Summary section of the Alpine Quick Start page and should be updated. However, obtaining this info isn't trivial, and may require manually inspecting slurm.conf. See the following comment for more info: [https://github.com/ResearchComputing/Documentation/pull/336#discussion_r1765733520](https://github.com/ResearchComputing/Documentation/pull/336#discussion_r1765733520)

**Comment by jreiland** [comment]
Fixed in PR #336

**Comment by b-reyes** [comment]
@jreiland addressed this!!
