### ISSUE TITLE
replace all "watch this video or read this text" with just a link to the video

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/Documentation#37]

**Comment by anderbubble** [comment]
I hadn't realized that the apparent embedded video player was actually just a screenshot of the youtube player due to a limitation in the GH wiki. I say we replace this entire thing, including the image, with an embedded video player of the youtube video, since rtd should be able to support that.

**Comment by dtrahan41** [comment]
Replaced images and text with the appropriate links.
