### ISSUE TITLE
Fair share

### ISSUE THREAD

**Issue by knuths** [ResearchComputing/Documentation#40]
I don't think the fair share priority information on the FAQ is right.  Isn't the information for Level FS backward?  In other words, if you're over 1 you're over priority?

**Comment by knuths** [comment]
This doesn’t reflect what I see. For example my Level FS is 0.000049. I rarely run jobs. I’m finding this hard to understand and I don’t think it’s accurate.

On Oct 16, 2018, at 6:25 PM, Daniel Trahan <notifications@github.com<mailto:notifications@github.com>> wrote:


According to the Slurm documentation, LevelFS from 0 to 1 are overserviced accounts. Numbers from 1 to infinity are underserved accounts, with completely unused accounts set to infinity.

https://slurm.schedmd.com/sshare.html

**Comment by dtrahan41** [comment]
Made modifications to docs that will hopefully clarify sshare.
