### ISSUE TITLE
FAQ issues

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/Documentation#43]
"Using the Summit module environment from login nodes requires typing module load slurm/summit. "
This is only needed to switch to slurm/blanca or back from slurm/blanca (and I do not know about Viz but maybe we leave Viz out of the docs until the dust settles there).  Also you can use what little Modules are available on login w/o loading a module first, if that's what this is suggesting.

"Where is my current fair share priority level at?" - Maybe "How can I see my current FairShare priority?"

"I have a new phone. How do I move my Duo onto it?
You can add a new device to your duo account by visiting https://duo.colorado.edu. After a CU authorization page you will be directed to a Duo authentication page. From here, click “Menu”:"
- Actually it's "Settings" and not "Menu", as indicated in the graphic.  Otherwise this is great!  People have a lot of trouble with this somewhat confusing interface.

**Comment by dtrahan41** [comment]
Fixed the errors you pointed out. Thanks for the feedback!
