### ISSUE TITLE
Duo instructions need to be updated

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/Documentation#50]
https://curc.readthedocs.io/en/latest/access/duo-cu.html
"Open your duo invitation email (from duo security or duo.com) on a desktop/laptop computer
If you didn’t receive an invitation or your invitation has expired, then contact rc-help@colorado.edu for a new invitation."
This should say "within one business day you should receive a Duo invitation email.  If you do not receive an invitation..."

"Do not request a phone call instead of Push for authentication."
Do not request a phone call if you want to use the Push app for authentication.

"Each login will need to be approved and confirmed (two presses) through the duo app."
(no longer the case, it's just one press)
"Duo accounts are purged if unused for 3-6 months."
It's now 9 months so I suggest "6-9 months."

We could also link or add info about self-managing the devices via duo.colorado.edu

**Comment by dtrahan41** [comment]
Modifications have been made to dev.

**Comment by dtrahan41** [comment]
Dev has been merged, issue has been resolved
