### ISSUE TITLE
Edit to Job Submissions page for shas-testing

### ISSUE THREAD

**Issue by rctraining** [ResearchComputing/Documentation#51]
Change the QoS table for shast-testing (in 'Job submission' in the docs, so that 'Node limits' are changed from `2/user; max 12 cores/node` to `24 cores on up to 24 nodes`

**Comment by anderbubble** [comment]
I suggest

> 24 cores _across_ up to 24 nodes

**Comment by dtrahan41** [comment]
Updated in dev branch, will keep this open until everything is confirmed

**Comment by dtrahan41** [comment]
Dev pushed, problem is resolved
