### ISSUE TITLE
Add information about how to run on 10G RoCE nodes 

### ISSUE THREAD

**Issue by wilshire461** [ResearchComputing/Documentation#53]
Recently we got a few nodes with 10G Ethernet that also has the capability to do RoCE v2, allowing for users of those nodes to run MPI jobs over the ethernet network connecting them.

We should add some documentation to the website that informs users of how to compile codes that can run on the RoCE enabled network, and ensure that we have an MPI or two in modules that can be used to compile codes.

I'll start a PR, but will need some help in placing it in the right spot in the documentation.

**Comment by wilshire461** [comment]
I have create a MR for this issue #54
I still need to grab the module keys to put in this documentation from Aaron

**Comment by dtrahan41** [comment]
RoCE Nodes has been added to the documentation. Thanks for that!
