### ISSUE TITLE
Add tab for "Acknowledging RC resources"

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#55]
Use of University of Colorado Research Computing resources, including (but not limited to) the Janus and Summit supercomputers, the Blanca Condo Cluster, and the PetaLibrary data storage service must be acknowledged in any and all publications.

Acknowledging Summit:
"This work utilized the Summit supercomputer, which is supported by the National Science Foundation (awards ACI-1532235 and ACI-1532236), the University of Colorado Boulder, and Colorado State University. The Summit supercomputer is a joint effort of the University of Colorado Boulder and Colorado State University."

Acknowledging Janus:
<Joel to provide text>

Acknowledging Blanca:
<Do we have text for this?>

Acknowledging PetaLibrary:
"Data storage supported by the University of Colorado Boulder 'PetaLibrary'"

**Comment by monaghaa** [comment]
Dan, I forgot to assign this previously

**Comment by dtrahan41** [comment]
Added but still missing the Blanca text

**Comment by dtrahan41** [comment]
Still missing Blanca blurb here, any info on this?

**Comment by monaghaa** [comment]
Thanks. Here's a revised version of the text that has a few tweaks (deleted Janus) and also included Blanca: 

----

Use of University of Colorado Research Computing resources, including (but not limited to) the Summit supercomputer, the Blanca Condo Cluster, and the PetaLibrary data storage service must be acknowledged in all publications.

Acknowledging Summit:
"This work utilized the Summit supercomputer, which is supported by the National Science Foundation (awards ACI-1532235 and ACI-1532236), the University of Colorado Boulder, and Colorado State University. The Summit supercomputer is a joint effort of the University of Colorado Boulder and Colorado State University."

Acknowledging Blanca:
"This work utilized the Blanca condo cluster, which is partially supported by the University of Colorado Boulder"

Acknowledging PetaLibrary:
"Data storage for this work is supported by the University of Colorado Boulder PetaLibrary"
