### ISSUE TITLE
Revise allocations request webpage text

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#62]
https://www.colorado.edu/rc/userservices/allocations

Please change: 

1. Please fill out the below template when constructing an allocation request for Summit. Be sure to address each bullet point in this worksheet. If you feel that some of the requested information is not applicable, please note why that is rather than leaving that section out of your request entirely. (PDF) (Latex) (Word)  Read the Scaling Analysis Appendix for more information. 

to (note * indicates bold text):

"1. *For best results and to reduce iterations, contact us at rc-help@colorado.edu before constructing an allocation request for RMACC Summit.*  

Once you've communicated with us you will fill out this allocation request worksheet (PDF) (Latex) (Word). Be sure to address each bullet point in this worksheet. Note that estimates of resources you need must be based on test jobs that you've run on Summit; we will not accept estimates based on jobs run on other HPC resources. More information on how to generate your resource estimates are in the Scaling Analysis Appendix."

**Comment by beckyyeager** [comment]
These changes have been made. Changes to the website should go through me and changes to documentation should go through Daniel
