### ISSUE TITLE
Add GNU Parallel Documentation to readthedocs

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#63]
https://docs.google.com/document/d/1KRFVASEq_QpxldcB0xwGh2Vs4-3NHLFhGO9qPl44b1w/edit#heading=h.p6ifrgyxntkt

**Comment by monaghaa** [comment]
Hi Dan, 

Here is the documentation for GNU Parallel. Jonathon and I have both vetted it.  I think it is ready to be posted on readthedocs (feel free to make any changes you want). 

Andy

**Comment by dtrahan41** [comment]
Added
