### ISSUE TITLE
Change "rc_username" to "username" on readthedocs "Data Transfer" pages

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#68]
A user requested that we replace "rc_username" with "username" at https://curc.readthedocs.io/en/latest/compute/data-transfer.html to avoid confusion. This seems like a reasonable request.  See additional details in her message, pasted below.

hello,
thank you for your help. replacement of rc_elvi8727@login.rc.colorado.edu by elvi8727@login.rc.colorado.edu helped. 
Can you then correct the webpage https://curc.readthedocs.io/en/latest/compute/data-transfer.html
[https://curc.readthedocs.io/en/latest/compute/data-transfer.html]
[https://curc.readthedocs.io/en/latest/compute/data-transfer.html]
Secure File Transfer Protocol (SFTP)
The Secure File Transfer Protocol is an interactive terminal solution to transfer data to and from research computing resources. SFTP works much like moving files in a terminal, we use a series of file system commands to navigate, move, remove, and copy information from a client's personal machine to research computing resources. To invoke SFTP type the command:
sftp rc_username@login.rc.colorado.edu

We can then use various commands to traverse and manipulate both file systems. A list of commands are listed below:
[https://curc.readthedocs.io/en/latest/compute/data-transfer.html]
[https://curc.readthedocs.io/en/latest/compute/data-transfer.html]
Data transfer - Research Computing University of Colorado Boulder documentation - curc.readthedocs.io [https://curc.readthedocs.io/en/latest/compute/data-transfer.html]
curc.readthedocs.io
Globus¶. On Globus, file transfers are handled through an interactive web application. Globus addresses deficiencies in secure copy requests by automating large data transfers, resuming failed transfers, and simplifying the implementation of high performance transfers between computing centers.

So other users don't get confused as well.
Thanks,

**Comment by dtrahan41** [comment]
Made the modifications, let me know if you find anything else
