### ISSUE TITLE
Correction to Matlab parfor documentation

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#79]
Would it be possible to delete "int" from "parfor(int i <other stuff>)" so that it reads "parfor(i <other stuff>)" in two locations on https://curc.readthedocs.io/en/latest/software/matlab.html.

Reason: A user pointed out that the loop doesn't work with "int", and on inspection it appears that "int" is used in the generic documentation for parfor to point out that the loop counter should be an integer.

**Comment by dtrahan41** [comment]
Fixed in latest Merge
