### ISSUE TITLE
Replace references to "/work" with "/pl/active" throughout documentation

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#82]
I suspect that this mainly will require edits to this page:

https://curc.readthedocs.io/en/latest/compute/petalibrary.html#accessing-the-petalibrary

Although there may be other references in the docs. 

Here's the motivation for this request (From a user ticket):

"The issue was that I was accessing our storage through
the /work directory, not /pl/active. I'm not seeing any documentation
through curc that states that, only documentation for using the /work
directory (link
<https://curc.readthedocs.io/en/latest/compute/petalibrary.html#accessing-the-petalibrary>).
It may be helpful to add/update this documentation."

**Comment by dtrahan41** [comment]
Fixed in latest Merge
