### ISSUE TITLE
Update Blanca Node Features Table

### ISSUE THREAD

**Issue by monaghaa** [ResearchComputing/Documentation#84]
Would it be possible to add the new Blanca HPC nodes?  They include:

"blanca-curc" (3 nodes)
"blanca-nso" (36 nodes)
"blanca-topopt" (5 nodes).  Note that these same five nodes are also named "blanca".  I'm seeking clarification on the difference between "blanca" and "blanca-topopt".

**Comment by monaghaa** [comment]
In reference to my request above, I'm following up to node that "blanca" does not need to be added to the Node Feature table.  Just the other three.

**Comment by dtrahan41** [comment]
Added!
