### ISSUE TITLE
Wrong bash syntax in compile docs

### ISSUE THREAD

**Issue by jamesETsmith** [ResearchComputing/Documentation#85]
Hi All,

While trying to compile an hdf5 example I found was using the docs and found that the following compile command
```bash
$FC my_program.f90 -I$(CURC_HDF5_INC) -L$(CURC_HDF5_LIB) -lhdf5_fortran -o my_program
```

I tried to adapt it for my own use and when I did I encountered some errors, shown below:

```bash
(base) jasm3285@shas0136:hdf5$ mpiicc example.cpp -I$(CURC_HDF5_INC) -L$(CURC_HDF5_LIB) -lhdf5 -o example
-bash: CURC_HDF5_INC: command not found
-bash: CURC_HDF5_LIB: command not found
```
After looking a bit closer I saw that you used `$(CURC_HDF5_INC)`, which I think is for bash commands, not variables. When I switched `${CURC_HDF5_INC}`, the program compiles successfully.

My final successful command is 

```bash
mpiicc example.cpp -I${CURC_HDF5_INC} -L${CURC_HDF5_LIB} -lhdf5 -o example
````

**Comment by dtrahan41** [comment]
Thanks for pointing this out! I have added the changes to dev and it will be pushed in a bit
